name: AutoNav_Sim CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ros-humble-ci:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop-full

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions python3-pip python3-pytest-cov
          rosdep update
          rosdep install --from-paths src --ignore-src -y

      - name: Linting (ament_lint)
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash

          # Build with tests enabled
          colcon build \
            --packages-select my_bot \
            --cmake-args -DBUILD_TESTING=ON

          # Run tests (ament_lint_auto runs here)
          colcon test --packages-select my_bot --return-code-on-test-failure
          colcon test-result --verbose

      - name: Code Coverage
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash

          python3 -m pytest \
            --cov=src/my_bot/my_bot \
            --cov-report=xml \
            src/my_bot/test/
        continue-on-error: true

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
